const OWNER_RESTAURANT_MAP = {
  'spicegarden@moodbyte.com': '1',
  'pizzaparadise@moodbyte.com': '2',
  'greenbowl@moodbyte.com': '3',
  'dragonwok@moodbyte.com': '4',
  'burgerbarn@moodbyte.com': '5',
  'biryanihouse@moodbyte.com': '6',
  'sweettooth@moodbyte.com': '7',
  'soulandsoul@moodbyte.com': '8',
  'tacotierra@moodbyte.com': '9',
  'sushiharbor@moodbyte.com': '10',
  'curryleaf@moodbyte.com': '11',
  'pholotus@moodbyte.com': '12',
  'mediterraneo@moodbyte.com': '13',
  'kebabcourt@moodbyte.com': '14',
  'pastafresca@moodbyte.com': '15',
  'norihouse@moodbyte.com': '16',
  'graingreens@moodbyte.com': '17',
  'wafflenest@moodbyte.com': '18',
  'smokehouse19@moodbyte.com': '19',
  'coconutcoast@moodbyte.com': '20',
  'veggievault@moodbyte.com': '21',
  'dumplingden@moodbyte.com': '22',
  'ramenrealm@moodbyte.com': '23',
  'bistrobloom@moodbyte.com': '24',
  'rollhouse@moodbyte.com': '25',
  'cielocafe@moodbyte.com': '26',
  'heritagethali@moodbyte.com': '27',
  'seoulstreet@moodbyte.com': '28',
  'falafelfarm@moodbyte.com': '29',
  'crispcorner@moodbyte.com': '30',
};

module.exports = OWNER_RESTAURANT_MAP;